Passing sql file paths
bryzgaloff/airflow-clickhouse-plugin pull request #62
Opened 2022-12-28 17:18 UTC by MaximTar

Tried to take into account your comments in the https://github.com/bryzgaloff/airflow-clickhouse-plugin/pull/41
(Besides, fixed badge in the README and patched workflow)

2023-01-03 09:47 UTC, bryzgaloff requested changes
Thank you for your contribution! Have some questions and suggestions, please request my review again once done.

2023-01-03 09:47 UTC, bryzgaloff commented on tests/unit/test_operator.py
> +DEFAULT_DATE = datetime.datetime.now()
```suggestion
_TEST_START_DATE = datetime.datetime.now()
```

2023-01-03 09:47 UTC, bryzgaloff commented on tests/unit/test_operator.py
> +DEFAULT_DATE = datetime.datetime.now()
Looks more descriptive to me

2023-01-03 09:47 UTC, bryzgaloff commented on tests/unit/test_operator.py
> +            task._sql = template_file
Why do you override `task._sql` here and not simply set `sql` to `template_file` in the `ClickHouseOperator` constructor? I am not quite familiar with files functionality in Airflow, and I would assume `ClickHouseOperator(task_id='test_task', sql=template_file)` to work fine.

2023-01-03 09:47 UTC, bryzgaloff commented on tests/unit/test_operator.py
> +        with NamedTemporaryFile(suffix='.sql') as f:
```suggestion
        with NamedTemporaryFile(suffix='.sql') as sql_file:
```

2023-01-03 09:47 UTC, bryzgaloff commented on tests/unit/test_operator.py
> +            template_file = os.path.basename(f.name)
```suggestion
            sql_file_dir = os.path.dirname(sql_file.name)
            sql_file_name = os.path.basename(sql_file.name)
```

2023-01-03 09:47 UTC, bryzgaloff commented on tests/unit/test_operator.py
> +            template_file = os.path.basename(f.name)
Please apply the same changes to other tests too

2023-01-16 09:58 UTC, bryzgaloff approved these changes
Well done, thank you! I will include this in the next release 👍

2023-01-16 09:59 UTC, bryzgaloff commented
Also, adding you as a contributor, of course

2023-01-16 10:00 UTC, merged

2023-01-16 15:54 UTC, MaximTar commented
> Also, adding you as a contributor, of course

Thanks, happy to help!
I hope you will have time to look at #63 also

2023-01-29 04:05 UTC, bryzgaloff commented
Hey @MaximTar I wanted to publish this PR's update as the next version using your awesome #63 work, but looks like we need som extra changes to #63. It this functionality (SQL files paths) urgent for you? I may publish it manually, if required, or we may wait till the publishing PR is ready to test it right away :)

2023-03-23 12:59 UTC, darkebe commented
Hello, thanks for this PR @MaximTar 
Do you know when this will be release ?

2023-03-24 07:15 UTC, bryzgaloff commented
Hi @darkebe I was expecting #63 to be implemented to deploy this feature, but looks like we are stuck with the automated publishing to PyPI. Thus, I plan to publish the feature manually till early next week.

2023-03-26 13:27 UTC, MaximTar commented
> 

I apologize that I disappeared - a blockage formed on all fronts, from which I just started to get out
now back to my request

2023-03-27 07:55 UTC, bryzgaloff commented
No problem, your participation is highly appreciated! :)

I have just published this version manually as v0.10.1: https://github.com/bryzgaloff/airflow-clickhouse-plugin/releases/tag/v0.10.1

CC @darkebe @MaximTar